<?php

$listarray = array ( 
                     array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 100, 
                             'type' => 'date',
                             'inctime' => 'true',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Erl-Datum',
                             'name' => 'erldatum', 
                             'width' => 100, 
                             'type' => 'date',
                             'fieldhide' => 'true',
                             'inctime' => 'true',
                             'dbfield' => 'flderldatum' ),
                     array ( 'label' => 'Nr',
                             'name' => 'nr',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldnr' ),
                     array ( 'label' => 'Thema',
                             'name' => 'thema',
                             'width' => 500, 
                             'type' => 'text',
                             'linkfield' => 'fldlink',
                             'targetfield' => 'fldTarget',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Bemerkung',
                             'name' => 'bemerk',
                             'width' => 10, 
                             'type' => 'textarea',
                             'fieldhide' => 'true',
                             'dbfield' => 'fldbemerk' ),
                     array ( 'label' => 'Link',
                             'name' => 'link',
                             'fieldhide' => 'true',
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldlink' ),
                     array ( 'label' => 'Target',
                             'name' => 'target',
                             'fieldhide' => 'true',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldTarget' ),
                     array ( 'label' => 'File',
                             'name' => 'file',
                             'width' => 500, 
                             'type' => 'text',
                             'fieldhide' => 'true',
                             'dbfield' => 'fldfilename' ),
                     array ( 'label' => 'Gruppe',
                             'name' => 'gruppe',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_gruppe' ),
/*
                     array ( 'label' => 'Themen',
                             'name' => 'themen',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblthemen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_themen' ),
                     array ( 'label' => 'Status',
                             'name' => 'status',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'fieldhide' => 'true1',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ),
*/
                     array ( 'label' => 'Datei',
                             'width' => 5, 
                             'type' => 'iconempty',
                             'fieldprthide' => 'true',
                             'dbfield' => 'fldfilename' ),
                     array ( 'label' => 'Timestamp',
                             'name' => 'timestamp', 
                             'width' => 10, 
                             'type' => 'text',
                             'fieldhide' => 'true1',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldtimestamp' ),
                     array ( 'label' => 'dbsync',
                             'name' => 'dbsync', 
                             'width' => 100, 
                             'type' => 'text',
                             'fieldsave' => 'NO',
                             'dbfield' => 'flddbsyncstatus' ));


$filterarray = array ( array ( 'label' => 'Gruppe:',
                             'name' => 'gruppe', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'selwhere' => 'fldindex in (select fldid_gruppe from tblnotiz)',
                             'dbfield' => 'fldid_gruppe' ));
/*
                     array ( 'label' => 'Themen:',
                             'name' => 'fltthemen', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblthemen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'selwhere' => 'fldindex in (select fldid_themen from tblnotiz)',
                             'dbfield' => 'fldid_themen' ),
                     array ( 'label' => 'Status:',
                             'name' => 'fltstatus', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ),
                     array ( 'label' => 'Datum:',
                             'name' => 'fltdatum',
                             'value' => '', 
                             'width' => 500, 
                             'type' => 'date',
                             'sign' => '=',                              
                             'dbfield' => 'flddatum' ));
*/

$pararray = array ( 'headline' => 'Notizen',
                    'dbtable' => 'tblnotiz',
                    'orderby' => 'fldnr,flddatum',
                    'editonlogin1' => 'true',
                    'dbsyncnr' => 'J',
//                    'strwhere' => "fldarchivdat='0000-00-00'",
                    'fldindex' => 'fldindex');

?>