<?php
$listarray = array ( array ( 'label' => 'Barcode',
                             'name' => 'barcode',      
                             'width' => 100, 
                             'type' => 'text',
							        'schnellerfass' => 'key',
							        'barcode' => 'YES',
                             'dbfield' => 'fldbarcode' ),
                     array ( 'label' => 'Artikel',
                             'name' => 'artikel', 
                             'width' => 50, 
							        'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblartikel',
                             'seldbfield' => 'fldbarcode',
                             'selfield' => 'fldbarcode',
							        'seldbbez' => 'fldBez',
                             'dbfield' => 'flddummy' ),
                     array ( 'label' => 'Ort (kurz)',
                             'name' => 'ortkurz', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'text',
							        'schnellerfass' => 'ort',
                             'dbfield' => 'fldortkurz' ),
                     array ( 'label' => 'Ort',
                             'name' => 'ortbez', 
                             'width' => 50, 
							        'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblortkurz',
                             'seldbfield' => 'fldkurz',
                             'selfield' => 'fldortkurz',
							        'seldbbez' => 'fldbez',
                             'dbfield' => 'flddummy1' ),
                     array ( 'label' => 'Zimmer',
                             'name' => 'zimmer', 
                             'width' => 500, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'sign' => '=',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldid_zimmer' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz',      
                             'width' => 20, 
                             'type' => 'text',
							        'schnellerfass' => 'anz',
                             'dbfield' => 'fldanz' ),
                     array ( 'label' => 'ME',
                             'name' => 'mengein', 
                             'width' => 50, 
							        'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblartikel',
                             'seldbfield' => 'fldbarcode',
                             'selfield' => 'fldbarcode',
							        'seldbbez' => 'fldverpackbez',
                             'dbfield' => 'flddummy2' ),
                     array ( 'label' => 'Mind.halt.-Datum',
                             'name' => 'mhdatum',      
                             'width' => 20, 
                             'type' => 'date',
                             'dbfield' => 'fldmhdatum' ),
                     array ( 'label' => 'Timestamp',
                             'name' => 'fldtimestamp', 
                             'width' => 100, 
                             'type' => 'text',
                             'fieldhide' => 'true1',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldtimestamp' ),
                     array ( 'label' => 'dbsyncstatus',
                             'name' => 'dbsyncstatus',
                             'width' => 20, 
                             'fieldsave' => 'NO',
                             'type' => 'text',
                             'dbfield' => 'flddbsyncstatus' ));

/*
$filterarray = array ( array ( 'label' => 'Artikel:',
                               'name' => 'fltartikel', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblartikel',
                               'seldbfield' => 'fldbarcode',
                               'dbfield' => 'fldbarcode' ),
                       array ( 'label' => 'Von Ort:',
                               'name' => 'fltvonortkurz', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '>=',
                               'dbtable' => 'tblortkurz',
                               'seldbfield' => 'fldkurz',
                               'dbfield' => 'fldortkurz' ),
                       array ( 'label' => 'Bis Ort:',
                               'name' => 'fltbisortkurz', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '<=',
                               'dbtable' => 'tblortkurz',
                               'seldbfield' => 'fldkurz',
                               'dbfield' => 'fldortkurz' ));							 
*/

$pararray = array ( 'headline' => 'Vorrat',
                    'dbtable' => 'tblvorrat',
                    'orderby' => 'fldortkurz,fldbarcode',
                    'strwhere' => '',
                    'markseldb' => 'J',
                    'markseltyp' => 'date',
                    'dbsyncnr' => 'J',
                    'fldindex' => 'fldindex');

?>