<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Erledigung',
                             'name' => 'TASK',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Gruppe',
                             'name' => 'GROUP',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select1',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldborder' => 'fldbez',
                             'dbfield' => 'fldGruppe' ),
                     array ( 'label' => 'Kategorie',
                             'name' => 'kategorie',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select',
                             'dbtable' => 'tblkategorie',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldcategory' ),
                     array ( 'label' => 'Thema',
                             'name' => 'themen',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'selectid',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_erlgrp' ),
                     array ( 'label' => 'Anz',
                             'name' => 'detail', 
                             'width' => 5, 
                             'type' => 'detail',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Pr',
                             'name' => 'pr', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblprior',
                             'seldbfield' => 'fldprior',
                             'dbfield' => 'fldprior' ),
                     array ( 'label' => 'Status',
                             'name' => 'status', 
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldstatus' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 50, 
                             'type' => 'date',
                             'default' => 'now()',
                             'dbfield' => 'fldDatum' ),
                     array ( 'label' => 'Erl.-Datum',
                             'name' => 'erldatum', 
                             'getdefault' => 'true',
                             'fieldhide' => 'true',
                             'fieldprthide' => 'true',
                             'width' => 50, 
                             'type' => 'date',
                             'dbfield' => 'fldErledigDat' ),
                     array ( 'label' => 'Eintrag von',
                             'name' => 'eintrag', 
                             'getdefault' => 'true',
                             'width' => 100, 
                             'type' => 'select1',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldBenutzer' ));

$filterarray = array ( 
                       array ( 'label' => 'Status:',
                               'name' => 'status', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblstatus',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldstatus' ),
                       array ( 'label' => 'Kategorie:',
                               'name' => 'fltkategorie', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblkategorie',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldcategory' ),
                       array ( 'label' => 'Thema:',
                               'name' => 'fltthema', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblgrperl',
                               'seldbfield' => 'fldbez',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_erlgrp' ),
                       array ( 'label' => 'Prior:',
                               'name' => 'fltprior', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblprior',
                               'seldbfield' => 'fldprior',
                               'dbfield' => 'fldprior' ));


$pararray = array ( 'headline' => 'Erledigungen',
                    'name' => 'TASK',
                    'dbtable' => 'tblerledigungen',
                    'fldindex' => 'fldIndex');

?>