<?php

$listarray = array ( array ( 'label' => 'ID',
                             'width' => 10, 
                             'type' => 'show',
                             'dbfield' => 'fldindex' ),
                     array ( 'label' => 'Sort',
                             'name' => 'Sort',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldsort' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'Bezeichung',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                    array ( 'label' => 'Menü',
                             'name' => 'menu',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldmenu' ),
                    array ( 'label' => 'Link',
                             'name' => 'link',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldlink' ),
                    array ( 'label' => 'Parameter',
                             'name' => 'param',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldparam' ),
                    array ( 'label' => 'Parent',
                             'name' => 'idparent',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldid_parent' ),
                    array ( 'label' => 'Icon',
                             'name' => 'glyphicon',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldglyphicon' ),
                    array ( 'label' => 'Sprache',
                             'name' => 'language',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldlanguage' ),
                     array ( 'label' => 'Anzeigen',
                             'name' => 'anzeigen',
                             'default' => 'N',
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblsel',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldview' ));

$filterarray = array ( array ( 'label' => 'Sprache',
                               'name' => 'fltsprache', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblsprache',
                               'seldbfield' => 'fldlanguage',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldlanguage' ),
                       array ( 'label' => 'Anzeige:',
                               'name' => 'fltanzeige', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblsel',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldview' ));


$pararray = array ( 'headline' => 'Menü',
                    'name' => 'menu',
                    'dbtable' => 'tblmenu_liste',
                    'orderby' => 'fldsort',
                    'markfield' => 'fldview',
                    'markyes' => 'J',
                    'markno' => 'N',
                    'fldindex' => 'fldindex');

?>