<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Barcode',
                             'name' => 'barcode',
                             'width' => 100, 
                             'fieldhide' => 'true',
                             'type' => 'text',
                             'dbfield' => 'fldBarcode' ),
                     array ( 'label' => 'Konto',
                             'name' => 'konto', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblktokonten',
                             'seldbfield' => 'fldKurz',
                             'dbfield' => 'fldKonto' ),
                     array ( 'label' => 'Kaufort',
                             'name' => 'kaufort', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbwhere' => "fldo01typ='FREMD'",
                             'dbfield' => 'fldOrt' ),
                     array ( 'label' => 'Abteilung',
                             'name' => 'abteilung', 
                             'getdefault' => 'true',
                             'width' => 100, 
                             'default' => '(ohne)',
                             'type' => 'select1',
                             'sign' => '=',
                             'dbtable' => 'tblabteilung',
                             'seldbfield' => 'fldAbteilung',
                             'dbfield' => 'fldAbteilung' ),
                     array ( 'label' => 'Status',
                             'name' => 'status',
                             'width' => 10, 
                             'default' => 'offen',
                             'type' => 'select',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldStatus' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz',
                             'default' => 1, 
                             'width' => 5, 
                             'type' => 'text',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => 'E-Preis',
                             'name' => 'epreis', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => 'G-Preis',
                             'name' => 'gpreis', 
                             'width' => 10, 
                             'type' => 'calc',
                             'calcfield' => 'fldAnz',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => 'Datum',
                             'name' => 'einkaufsdatum', 
                             'width' => 10, 
                             'type' => 'date',
                             'fieldhide' => 'true',
                             'default' => 'now()',
                             'dbfield' => 'fldEinkaufDatum' ),
                     array ( 'label' => 'Uhrzeit',
                             'name' => 'einkaufsuhrzeit', 
                             'width' => 10, 
                             'type' => 'time',
                             'fieldhide' => 'true',
                             'default' => 'now()',
                             'dbfield' => 'fldEinkaufUhrzeit' ),
                     array ( 'label' => 'Archivdatum',
                             'name' => 'archivdatum', 
                             'width' => 10, 
                             'type' => 'text',
                             'fieldhide' => 'true',
                             'default' => '',
                             'dbfield' => 'fldArchivDat' ),
                     array ( 'label' => 'Timestamp',
                             'name' => 'timestamp', 
                             'width' => 10, 
                             'type' => 'text',
                             'fieldhide' => 'true1',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldtimestamp' ),
                     array ( 'label' => 'P',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'preisspeichern.php?menu=shopping',
                             'dbfield' => 'icon-book' ));

$filterarray = array ( 
                       array ( 'label' => 'Status:',
                               'name' => 'status', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblstatus',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldStatus' ),
                       array ( 'label' => ' Kaufort:',
                               'name' => 'kaufort', 
                               'addfunc' => 'true',
                               'funcsetbutton' => 'true',
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblorte',
                               'seldbwhere' => "fldo01typ='FREMD'",
                               'seldbfield' => 'fldBez',
                               'dbfield' => 'fldort' ),
                       array ( 'label' => ' Konto:',
                               'name' => 'fltkonto', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblktokonten',
                               'seldbfield' => 'fldKurz',
                               'dbfield' => 'fldKonto' ));

$pararray = array ( 'headline' => 'Einkaufsliste',
                    'dbtable' => 'tblEinkauf_liste',
                    'addfunc' => 'true',
                    'fldarchivdat' => 'fldArchivDat',
                    'orderby' => 'fldort, fldBez',
                    'strwhere' => "fldArchivDat=''",
                    'fldindex' => 'fldIndex',
                    'fldbez' => 'fldBez',
                    'fldEinkaufDat' => 'fldEinkaufDat',
                    'strort' => 'J',
                    'chkpreis' => 'J',
                    'preisentw' => 'J',
                    'markbgcolor' => '88ff88',
                    'ummarkbgcolor' => 'ffffff',
                    'markyes' => 'OK',
                    'markno' => 'offen',
                    'marksign' => '=',
                    'markfield' => 'fldStatus');

?>