<?php
$listarray = array ( array ( 'label' => 'ID',
                             'name' => 'id',
                             'fieldsave' => 'NO',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldindex' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Pfad',
                             'name' => 'pfad',
                             'width' => 100, 
                             'fieldhide' => 'true',
                             'type' => 'text',
                             'dbfield' => 'fldPfad' ),
                     array ( 'label' => 'Wildcard',
                             'name' => 'wildcard',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldWildcard' ),
                     array ( 'label' => 'Gruppe',
                             'name' => 'gruppe',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'selectid',
                             'dbtable' => 'tblfmgrp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_fmgrp' ),
                     array ( 'label' => 'Files',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'filemanager.php?menu=filemanager',
                             'dbfield' => 'icon-book' ));
							 

$filterarray = array ( 
                       array ( 'label' => 'Gruppe:',
                               'name' => 'fltgrp', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblfmgrp',
                               'seldbfield' => 'fldbez',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_fmgrp' ));

                             
$pararray = array ( 'headline' => 'Dateimanager',
                    'dbtable' => 'tblfilemanager',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>